junit.framework.AssertionFailedError: an exception should have been thrown
